Update for new dnsmasq config generation method

diff --git a/keenetic-pbr/Makefile b/keenetic-pbr/Makefile
--- a/keenetic-pbr/Makefile
+++ b/keenetic-pbr/Makefile
@@ -69,6 +69,17 @@ KEENETIC_CONF="/opt/etc/keenetic-pbr/keenetic-pbr.conf"
 echo "Keenetic-pbr installation"
 echo "------------------------"
 
+if [ -f "$${KEENETIC_CONF}" ]; then
+	echo "Existing keenetic-pbr.conf found, upgrading it. Old config will be backed up to 'keenetic-pbr.conf.before-update'"
+	cp "$${KEENETIC_CONF}" "$${KEENETIC_CONF}.before-update"
+	keenetic-pbr upgrade-config || echo "keenetic-pbr config upgrade failed"
+fi
+
+# rm all files /opt/etc/dnsmasq.d/*.keenetic-pbr.conf
+echo "Removing old generated dnsmasq ipset configs (dnsmasq.d/*.keenetic-pbr.conf)"
+rm -f /opt/etc/dnsmasq.d/*.keenetic-pbr.conf
+rm -f /opt/etc/dnsmasq.d/*.keenetic-pbr.conf.md5
+
 # Backup existing config if present
 if [ -f "$${DNSMASQ_CONF}" ]; then
 	echo "Existing dnsmasq.conf found, backing up to '$$DNSMASQ_ORIGINAL_BAK'"
diff --git a/keenetic-pbr/opt/etc/init.d/S80keenetic-pbr b/keenetic-pbr/opt/etc/init.d/S80keenetic-pbr
--- a/keenetic-pbr/opt/etc/init.d/S80keenetic-pbr
+++ b/keenetic-pbr/opt/etc/init.d/S80keenetic-pbr
@@ -5,7 +5,7 @@
 log()
 {
   logger -t "keenetic-pbr" "$1"
-  echo "[keenetic-pbr] $1"
+  echo "${ansi_blue}[keenetic-pbr]${ansi_white} $1${ansi_std}" >&2
 }
 
 enable_hwnat()
@@ -24,14 +24,14 @@ disable_hwnat()
 
 apply_lists_and_routing()
 {
-  log "Applying lists and routing configuration..."
+  log "Applying routing configuration and importing IPs/CIDRs to ipsets..."
   $KEENETIC_PBR -config "$CONFIG" apply
 }
 
 apply_routing()
 {
   log "Applying routing configuration..."
-  $KEENETIC_PBR -config "$CONFIG" apply --skip-dnsmasq --skip-ipset
+  $KEENETIC_PBR -config "$CONFIG" apply -skip-ipset
 }
 
 unapply_routing()
@@ -40,11 +40,53 @@ unapply_routing()
   $KEENETIC_PBR -config "$CONFIG" undo-routing
 }
 
+start_dnsmasq()
+{
+  log "Starting dnsmasq with keenetic-pbr config..."
+  $DNSMASQ --conf-script /opt/etc/init.d/S80keenetic-pbr generate-dnsmasq-config || log "Failed to start dnsmasq"
+  log "dnsmasq started"
+}
+
+stop_dnsmasq()
+{
+  log "Stopping dnsmasq..."
+  /opt/etc/init.d/S56dnsmasq stop || true
+}
+
 restart_dnsmasq()
 {
-  log "Restarting dnsmasq..."
-  /opt/etc/init.d/S56dnsmasq restart
-  log "dnsmasq restarted"
+  stop_dnsmasq
+  start_dnsmasq
+}
+
+check_dnsmasq() {
+    echo -e -n "$ansi_white Checking dnsmasq... $ansi_std"
+
+    dnsmasq_pid=$(pidof $DNSMASQ)
+    if [ -n "$dnsmasq_pid" ]; then
+
+        if cat /proc/$dnsmasq_pid/cmdline | grep -- "generate-dnsmasq-config"; then
+            echo -e "            $ansi_green alive and configured by keenetic-pbr. $ansi_std";
+            return 0
+        else
+            echo -e "            $ansi_yellow alive but not configured by keenetic-pbr. $ansi_std";
+            echo -e "$ansi_yellow dnsmasq cmdline is '$(cat /proc/$dnsmasq_pid/cmdline)' $ansi_std";
+            return 1
+        fi
+
+    else
+        echo -e "            $ansi_red dead. $ansi_std";
+        return 1
+    fi
+}
+
+generate_dnsmasq_config()
+{
+  cat $DNSMASQ_CONFIG
+
+  echo ""
+  echo "# ipsets generated by keenetic-pbr below"
+  $KEENETIC_PBR -config "$CONFIG" print-dnsmasq-config
 }
 
 start()
@@ -58,6 +100,7 @@ stop()
 {
   enable_hwnat
   unapply_routing
+  stop_dnsmasq
 }
 
 case "$1" in
@@ -72,10 +115,10 @@ case "$1" in
     sleep 2
     start
     ;;
-  download-lists|download_lists)
+  download-lists|download_lists|update)
     log "Downloading lists..."
     $KEENETIC_PBR -config "$CONFIG" download
-    log "Lists downloaded. Please run '/opt/etc/init.d/S80keenetic-pbr apply-lists' to make use of them or restart OPKG."
+    log "Lists downloaded. Please run '/opt/etc/init.d/S80keenetic-pbr restart' to make use of them or restart OPKG."
     ;;
   apply-lists|apply_lists)
     apply_lists_and_routing
@@ -83,10 +126,16 @@ case "$1" in
   apply-routing|apply_routing)
     apply_routing
     ;;
-  self-check)
+  self-check|self_check)
     $KEENETIC_PBR -config "$CONFIG" self-check
     ;;
+  generate-dnsmasq-config)
+    generate_dnsmasq_config
+    ;;
+  check|status)
+    check_dnsmasq
+    ;;
   *)
-    echo "Usage: $0 {start|stop|restart|download-lists|apply-lists|apply-routing|self-check}"
+    echo "Usage: $0 {start|stop|restart|check|status|self-check|download-lists|apply-lists|apply-routing}"
     ;;
 esac
